=== lukaszimmermann/i2b2-fhir-cell/fhir-cell/dstu21/xquery/src/main/resources/transform/map/MapSystem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
	elementFormDefault="qualified" targetNamespace="http://i2b2.harvard.edu/map"
	xmlns:i="http://i2b2.harvard.edu/map" vc:minVersion="1.1">

	<xs:element name="MapSystemSet" type="i:MapSystemSet">
	</xs:element>
	<xs:element name="MapSystem" type="i:MapSystem">
	</xs:element>

	<xs:complexType name="MapSystemSet">
		<xs:sequence>
			<xs:element name="MapSystem" type="i:MapSystem" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MapSystem">
		<xs:sequence>
			<xs:element name="NameSpaceDeclaration" type="i:NameSpaceDeclaration" minOccurs="0"
				maxOccurs="unbounded" />
		
			<xs:element name="ToPath" type="i:ToPath" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="FromPath" type="i:FromPath" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="Map" type="i:Map" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>



	<xs:complexType name="Map">
		<xs:sequence>
			<xs:element name="ValueMap" type="i:ValueMap" minOccurs="1"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="defaultToValue" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="ValueMap">
		<xs:attribute name="to" type="xs:string" use="required" />
		<xs:attribute name="from" type="xs:string" use="required" />
	</xs:complexType>


	<xs:complexType name="ToPath">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" />
			<xs:element name="NameSystem" type="xs:string" />
			<xs:element name="Path" type="xs:string" />
			<xs:element name="DefaultGenerate" type="xs:boolean"
				default="false" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="FromPath">
		<xs:sequence>
			<xs:element name="Name" type="xs:string" />
			<xs:element name="NameSystem" type="xs:string" />
			<xs:element name="Path" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="NameSpaceDeclaration">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="uri" type="xs:string" use="required" />
	</xs:complexType>

</xs:schema>

=== lukaszimmermann/i2b2-fhir-cell/dstu21/xquery/src/main/resources/example/map/MapSystem1.xml
<?xml version="1.0" encoding="UTF-8"?>
<MapSystemSet xmlns="http://i2b2.harvard.edu/map"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://i2b2.harvard.edu/map ../../transform/MapSystem.xsd">
	<MapSystem>
		<NameSpaceDeclaration name="ns2" uri="http://www.i2b2.org/xsd/hive/pdo/1.1/" />
		
		<NameSpaceDeclaration name="f" uri="http://hl7.org/fhir" />
		<ToPath>
			<Name>maritalStatusCode</Name>
			<NameSystem>fhir</NameSystem>
			<Path>f:Patient/maritalStatus/Coding/Code</Path>
		</ToPath>
		<FromPath>
			<Name>gender</Name>
			<NameSystem>i2b2</NameSystem>
			<Path>/ns2:patient_set/patient/param[(@column='marital_status_cd')]/text()</Path>
		</FromPath>
		<Map defaultToValue="UNK">
			<ValueMap to="S" from="single"/>
			<ValueMap to="D" from="divorced"/>
			<ValueMap to="M" from="married"/>
			<ValueMap to="UNK" from="other"/>
			<ValueMap to="T" from="partner"/>
			<ValueMap to="L" from="seperated"/>
			<ValueMap to="UNK" from="unknown"/>
			<ValueMap to="UNK" from="widowed"/>
		</Map>
	</MapSystem>
	
</MapSystemSet>
